# Generated by Django 3.1.6 on 2021-02-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='education',
            name='description',
        ),
        migrations.AddField(
            model_name='education',
            name='gpa',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='education',
            name='major',
            field=models.CharField(default='', max_length=200),
        ),
    ]
