# Generated by Django 3.1.6 on 2021-02-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210218_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='major',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
